#############################################################################
# Makefile for building: cadence
# Generated by qmake (3.1) (Qt 6.4.2)
# Project:  AAE.pro
# Template: app
# Command: /usr/bin/qmake6 -o Makefile AAE.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DAPP_VERSION=\"0.1a\" -DAPP_NAME=\"Cadence\" -DQT_DISABLE_DEPRECATED_BEFORE=0x060000 -DQT_NO_DEBUG -DQT_OPENGLWIDGETS_LIB -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_SVG_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -fPIC -D_REENTRANT -Wall -Wextra $(DEFINES)
CXXFLAGS      = -pipe -Wall -Werror -flto -fno-strict-aliasing -O2 -std=gnu++1z -fPIC -D_REENTRANT -Wall -Wextra $(DEFINES)
INCPATH       = -I. -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtOpenGLWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtSvg -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake6
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake6 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake6 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = cadence0.1
DISTDIR = /home/abalore/hdd/Work/AAE/AAE/.tmp/cadence0.1
LINK          = g++
LFLAGS        = -flto -Wl,-O1 -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu
LIBS          = $(SUBLIBS) -lasound /usr/lib/x86_64-linux-gnu/libQt6OpenGLWidgets.so /usr/lib/x86_64-linux-gnu/libQt6OpenGL.so /usr/lib/x86_64-linux-gnu/libQt6Widgets.so /usr/lib/x86_64-linux-gnu/libQt6Svg.so /usr/lib/x86_64-linux-gnu/libQt6Gui.so /usr/lib/x86_64-linux-gnu/libGLX.so /usr/lib/x86_64-linux-gnu/libOpenGL.so /usr/lib/x86_64-linux-gnu/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Debugger.cpp \
		CRTScreen.cpp \
		DSK.cpp \
		FDC.cpp \
		FloppyDrive.cpp \
		Keyboard.cpp \
		PPI.cpp \
		PSG.cpp \
		Tape.cpp \
		Z80_16bitAL.cpp \
		Z80_8bitAL.cpp \
		Z80_8bitShift.cpp \
		Z80_IDX_3.cpp \
		Z80_Jump.cpp \
		Z80_Load.cpp \
		Z80_intexec.cpp \
		EmulatorThread.cpp \
		SoundThread.cpp \
		enterbytesdialog.cpp \
		graphicsinspector.cpp \
		main.cpp \
		mainwindow.cpp \
		CDT.cpp \
		CPC.cpp \
		CRTC.cpp \
		Machine.cpp \
		Disassembler.cpp \
		GateArray.cpp \
		Reg16.cpp \
		Z80.cpp \
		Z80_CB.cpp \
		Z80_IDX.cpp \
		Z80_IDX_2.cpp \
		Z80_IDX_CB.cpp \
		Z80_Instr.cpp \
		Z80_basic.cpp \
		Z80_misc.cpp \
		pboWidget.cpp \
		speedcontroller.cpp qrc_screen_frame.cpp \
		moc_Debugger.cpp \
		moc_EmulatorThread.cpp \
		moc_SoundThread.cpp \
		moc_enterbytesdialog.cpp \
		moc_graphicsinspector.cpp \
		moc_mainwindow.cpp
OBJECTS       = Debugger.o \
		CRTScreen.o \
		DSK.o \
		FDC.o \
		FloppyDrive.o \
		Keyboard.o \
		PPI.o \
		PSG.o \
		Tape.o \
		Z80_16bitAL.o \
		Z80_8bitAL.o \
		Z80_8bitShift.o \
		Z80_IDX_3.o \
		Z80_Jump.o \
		Z80_Load.o \
		Z80_intexec.o \
		EmulatorThread.o \
		SoundThread.o \
		enterbytesdialog.o \
		graphicsinspector.o \
		main.o \
		mainwindow.o \
		CDT.o \
		CPC.o \
		CRTC.o \
		Machine.o \
		Disassembler.o \
		GateArray.o \
		Reg16.o \
		Z80.o \
		Z80_CB.o \
		Z80_IDX.o \
		Z80_IDX_2.o \
		Z80_IDX_CB.o \
		Z80_Instr.o \
		Z80_basic.o \
		Z80_misc.o \
		pboWidget.o \
		speedcontroller.o \
		qrc_screen_frame.o \
		moc_Debugger.o \
		moc_EmulatorThread.o \
		moc_SoundThread.o \
		moc_enterbytesdialog.o \
		moc_graphicsinspector.o \
		moc_mainwindow.o
DIST          = /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_spatialaudio.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf \
		AAE.pro Debugger.h \
		CDT.h \
		CPC.h \
		CRTC.h \
		CRTScreen.h \
		DSK.h \
		Disassembler.h \
		FDC.h \
		FloppyDrive.h \
		GateArray.h \
		Keyboard.h \
		Machine.h \
		PPI.h \
		PSG.h \
		Reg16.h \
		Tape.h \
		Z80.h \
		defs.h \
		EmulatorThread.h \
		KeyPressFilter.h \
		SoundThread.h \
		enterbytesdialog.h \
		graphicsinspector.h \
		mainwindow.h \
		speedcontroller.h Debugger.cpp \
		CRTScreen.cpp \
		DSK.cpp \
		FDC.cpp \
		FloppyDrive.cpp \
		Keyboard.cpp \
		PPI.cpp \
		PSG.cpp \
		Tape.cpp \
		Z80_16bitAL.cpp \
		Z80_8bitAL.cpp \
		Z80_8bitShift.cpp \
		Z80_IDX_3.cpp \
		Z80_Jump.cpp \
		Z80_Load.cpp \
		Z80_intexec.cpp \
		EmulatorThread.cpp \
		SoundThread.cpp \
		enterbytesdialog.cpp \
		graphicsinspector.cpp \
		main.cpp \
		mainwindow.cpp \
		CDT.cpp \
		CPC.cpp \
		CRTC.cpp \
		Machine.cpp \
		Disassembler.cpp \
		GateArray.cpp \
		Reg16.cpp \
		Z80.cpp \
		Z80_CB.cpp \
		Z80_IDX.cpp \
		Z80_IDX_2.cpp \
		Z80_IDX_CB.cpp \
		Z80_Instr.cpp \
		Z80_basic.cpp \
		Z80_misc.cpp \
		pboWidget.cpp \
		speedcontroller.cpp
QMAKE_TARGET  = cadence
DESTDIR       = 
TARGET        = cadence


first: all
####### Build rules

cadence: ui_Debugger.h ui_enterbytesdialog.h ui_graphicsinspector.h ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: AAE.pro /usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_spatialaudio.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf \
		AAE.pro \
		screen_frame.qrc \
		/usr/lib/x86_64-linux-gnu/libQt6OpenGLWidgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt6OpenGL.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Svg.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Core.prl
	$(QMAKE) -o Makefile AAE.pro
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_linguist.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_spatialaudio.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_svgwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf:
AAE.pro:
screen_frame.qrc:
/usr/lib/x86_64-linux-gnu/libQt6OpenGLWidgets.prl:
/usr/lib/x86_64-linux-gnu/libQt6OpenGL.prl:
/usr/lib/x86_64-linux-gnu/libQt6Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt6Svg.prl:
/usr/lib/x86_64-linux-gnu/libQt6Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile AAE.pro

qmake_all: FORCE


all: Makefile cadence

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents screen_frame.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents Debugger.h CDT.h CPC.h CRTC.h CRTScreen.h DSK.h Disassembler.h FDC.h FloppyDrive.h GateArray.h Keyboard.h Machine.h PPI.h PSG.h Reg16.h Tape.h Z80.h defs.h EmulatorThread.h KeyPressFilter.h SoundThread.h enterbytesdialog.h graphicsinspector.h mainwindow.h speedcontroller.h $(DISTDIR)/
	$(COPY_FILE) --parents Debugger.cpp CRTScreen.cpp DSK.cpp FDC.cpp FloppyDrive.cpp Keyboard.cpp PPI.cpp PSG.cpp Tape.cpp Z80_16bitAL.cpp Z80_8bitAL.cpp Z80_8bitShift.cpp Z80_IDX_3.cpp Z80_Jump.cpp Z80_Load.cpp Z80_intexec.cpp EmulatorThread.cpp SoundThread.cpp enterbytesdialog.cpp graphicsinspector.cpp main.cpp mainwindow.cpp CDT.cpp CPC.cpp CRTC.cpp Machine.cpp Disassembler.cpp GateArray.cpp Reg16.cpp Z80.cpp Z80_CB.cpp Z80_IDX.cpp Z80_IDX_2.cpp Z80_IDX_CB.cpp Z80_Instr.cpp Z80_basic.cpp Z80_misc.cpp pboWidget.cpp pboWidget.h speedcontroller.cpp $(DISTDIR)/
	$(COPY_FILE) --parents Debugger.ui enterbytesdialog.ui graphicsinspector.ui mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_screen_frame.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_screen_frame.cpp
qrc_screen_frame.cpp: screen_frame.qrc \
		/usr/lib/qt6/libexec/rcc \
		spin.wav \
		tape.svg \
		step.wav \
		cartridge.svg \
		disk.svg \
		led_on.svg \
		monitor_frame.png \
		led_off.svg \
		cadence.svg
	/usr/lib/qt6/libexec/rcc -name screen_frame screen_frame.qrc -o qrc_screen_frame.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp
	g++ -pipe -Wall -Werror -flto -fno-strict-aliasing -O2 -std=gnu++1z -fPIC -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_Debugger.cpp moc_EmulatorThread.cpp moc_SoundThread.cpp moc_enterbytesdialog.cpp moc_graphicsinspector.cpp moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Debugger.cpp moc_EmulatorThread.cpp moc_SoundThread.cpp moc_enterbytesdialog.cpp moc_graphicsinspector.cpp moc_mainwindow.cpp
moc_Debugger.cpp: Debugger.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/abalore/hdd/Work/AAE/AAE/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/abalore/hdd/Work/AAE/AAE -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtOpenGLWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtSvg -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Debugger.h -o moc_Debugger.cpp

moc_EmulatorThread.cpp: EmulatorThread.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/abalore/hdd/Work/AAE/AAE/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/abalore/hdd/Work/AAE/AAE -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtOpenGLWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtSvg -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include EmulatorThread.h -o moc_EmulatorThread.cpp

moc_SoundThread.cpp: SoundThread.h \
		defs.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/abalore/hdd/Work/AAE/AAE/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/abalore/hdd/Work/AAE/AAE -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtOpenGLWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtSvg -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include SoundThread.h -o moc_SoundThread.cpp

moc_enterbytesdialog.cpp: enterbytesdialog.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/abalore/hdd/Work/AAE/AAE/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/abalore/hdd/Work/AAE/AAE -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtOpenGLWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtSvg -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include enterbytesdialog.h -o moc_enterbytesdialog.cpp

moc_graphicsinspector.cpp: graphicsinspector.h \
		defs.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/abalore/hdd/Work/AAE/AAE/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/abalore/hdd/Work/AAE/AAE -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtOpenGLWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtSvg -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include graphicsinspector.h -o moc_graphicsinspector.cpp

moc_mainwindow.cpp: mainwindow.h \
		EmulatorThread.h \
		SoundThread.h \
		defs.h \
		Debugger.h \
		graphicsinspector.h \
		enterbytesdialog.h \
		CPC.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/abalore/hdd/Work/AAE/AAE/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/abalore/hdd/Work/AAE/AAE -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtOpenGLWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtSvg -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_Debugger.h ui_enterbytesdialog.h ui_graphicsinspector.h ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_Debugger.h ui_enterbytesdialog.h ui_graphicsinspector.h ui_mainwindow.h
ui_Debugger.h: Debugger.ui \
		/usr/lib/qt6/libexec/uic
	/usr/lib/qt6/libexec/uic Debugger.ui -o ui_Debugger.h

ui_enterbytesdialog.h: enterbytesdialog.ui \
		/usr/lib/qt6/libexec/uic
	/usr/lib/qt6/libexec/uic enterbytesdialog.ui -o ui_enterbytesdialog.h

ui_graphicsinspector.h: graphicsinspector.ui \
		/usr/lib/qt6/libexec/uic
	/usr/lib/qt6/libexec/uic graphicsinspector.ui -o ui_graphicsinspector.h

ui_mainwindow.h: mainwindow.ui \
		/usr/lib/qt6/libexec/uic \
		pboWidget.h
	/usr/lib/qt6/libexec/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

Debugger.o: Debugger.cpp Debugger.h \
		ui_Debugger.h \
		EmulatorThread.h \
		Disassembler.h \
		defs.h \
		Z80.h \
		Reg16.h \
		PPI.h \
		CPC.h \
		Machine.h \
		CRTC.h \
		CRTScreen.h \
		GateArray.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debugger.o Debugger.cpp

CRTScreen.o: CRTScreen.cpp CRTScreen.h \
		defs.h \
		GateArray.h \
		Machine.h \
		CRTC.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CRTScreen.o CRTScreen.cpp

DSK.o: DSK.cpp DSK.h \
		defs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DSK.o DSK.cpp

FDC.o: FDC.cpp FDC.h \
		defs.h \
		FloppyDrive.h \
		DSK.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FDC.o FDC.cpp

FloppyDrive.o: FloppyDrive.cpp FloppyDrive.h \
		defs.h \
		DSK.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FloppyDrive.o FloppyDrive.cpp

Keyboard.o: Keyboard.cpp Keyboard.h \
		defs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Keyboard.o Keyboard.cpp

PPI.o: PPI.cpp PPI.h \
		defs.h \
		Z80.h \
		Reg16.h \
		CPC.h \
		Machine.h \
		CRTC.h \
		PSG.h \
		Keyboard.h \
		Tape.h \
		CDT.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PPI.o PPI.cpp

PSG.o: PSG.cpp PSG.h \
		defs.h \
		Keyboard.h \
		Tape.h \
		CDT.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PSG.o PSG.cpp

Tape.o: Tape.cpp Tape.h \
		defs.h \
		CDT.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Tape.o Tape.cpp

Z80_16bitAL.o: Z80_16bitAL.cpp Z80.h \
		defs.h \
		Reg16.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Z80_16bitAL.o Z80_16bitAL.cpp

Z80_8bitAL.o: Z80_8bitAL.cpp Z80.h \
		defs.h \
		Reg16.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Z80_8bitAL.o Z80_8bitAL.cpp

Z80_8bitShift.o: Z80_8bitShift.cpp Z80.h \
		defs.h \
		Reg16.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Z80_8bitShift.o Z80_8bitShift.cpp

Z80_IDX_3.o: Z80_IDX_3.cpp Z80.h \
		defs.h \
		Reg16.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Z80_IDX_3.o Z80_IDX_3.cpp

Z80_Jump.o: Z80_Jump.cpp Z80.h \
		defs.h \
		Reg16.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Z80_Jump.o Z80_Jump.cpp

Z80_Load.o: Z80_Load.cpp Z80.h \
		defs.h \
		Reg16.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Z80_Load.o Z80_Load.cpp

Z80_intexec.o: Z80_intexec.cpp Z80.h \
		defs.h \
		Reg16.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Z80_intexec.o Z80_intexec.cpp

EmulatorThread.o: EmulatorThread.cpp EmulatorThread.h \
		CPC.h \
		defs.h \
		Z80.h \
		Reg16.h \
		CRTScreen.h \
		Disassembler.h \
		SoundThread.h \
		speedcontroller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EmulatorThread.o EmulatorThread.cpp

SoundThread.o: SoundThread.cpp SoundThread.h \
		defs.h \
		PSG.h \
		FDC.h \
		FloppyDrive.h \
		DSK.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SoundThread.o SoundThread.cpp

enterbytesdialog.o: enterbytesdialog.cpp enterbytesdialog.h \
		ui_enterbytesdialog.h \
		CPC.h \
		defs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o enterbytesdialog.o enterbytesdialog.cpp

graphicsinspector.o: graphicsinspector.cpp graphicsinspector.h \
		defs.h \
		ui_graphicsinspector.h \
		GateArray.h \
		CPC.h \
		Machine.h \
		CRTC.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphicsinspector.o graphicsinspector.cpp

main.o: main.cpp mainwindow.h \
		EmulatorThread.h \
		SoundThread.h \
		defs.h \
		Debugger.h \
		graphicsinspector.h \
		enterbytesdialog.h \
		CPC.h \
		KeyPressFilter.h \
		Keyboard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		EmulatorThread.h \
		SoundThread.h \
		defs.h \
		Debugger.h \
		graphicsinspector.h \
		enterbytesdialog.h \
		CPC.h \
		ui_mainwindow.h \
		pboWidget.h \
		Tape.h \
		CDT.h \
		FDC.h \
		FloppyDrive.h \
		DSK.h \
		GateArray.h \
		CRTScreen.h \
		Keyboard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

CDT.o: CDT.cpp CDT.h \
		defs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CDT.o CDT.cpp

CPC.o: CPC.cpp CPC.h \
		defs.h \
		Machine.h \
		CRTC.h \
		GateArray.h \
		Keyboard.h \
		Z80.h \
		Reg16.h \
		PPI.h \
		PSG.h \
		FDC.h \
		FloppyDrive.h \
		DSK.h \
		Tape.h \
		CDT.h \
		CRTScreen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CPC.o CPC.cpp

CRTC.o: CRTC.cpp CRTC.h \
		defs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CRTC.o CRTC.cpp

Machine.o: Machine.cpp Machine.h \
		CRTC.h \
		defs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Machine.o Machine.cpp

Disassembler.o: Disassembler.cpp Disassembler.h \
		defs.h \
		CPC.h \
		Z80.h \
		Reg16.h \
		GateArray.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Disassembler.o Disassembler.cpp

GateArray.o: GateArray.cpp GateArray.h \
		defs.h \
		CPC.h \
		Machine.h \
		CRTC.h \
		Z80.h \
		Reg16.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GateArray.o GateArray.cpp

Reg16.o: Reg16.cpp Reg16.h \
		defs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Reg16.o Reg16.cpp

Z80.o: Z80.cpp Z80.h \
		defs.h \
		Reg16.h \
		CPC.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Z80.o Z80.cpp

Z80_CB.o: Z80_CB.cpp Z80.h \
		defs.h \
		Reg16.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Z80_CB.o Z80_CB.cpp

Z80_IDX.o: Z80_IDX.cpp Z80.h \
		defs.h \
		Reg16.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Z80_IDX.o Z80_IDX.cpp

Z80_IDX_2.o: Z80_IDX_2.cpp Z80.h \
		defs.h \
		Reg16.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Z80_IDX_2.o Z80_IDX_2.cpp

Z80_IDX_CB.o: Z80_IDX_CB.cpp Z80.h \
		defs.h \
		Reg16.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Z80_IDX_CB.o Z80_IDX_CB.cpp

Z80_Instr.o: Z80_Instr.cpp Z80.h \
		defs.h \
		Reg16.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Z80_Instr.o Z80_Instr.cpp

Z80_basic.o: Z80_basic.cpp Z80.h \
		defs.h \
		Reg16.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Z80_basic.o Z80_basic.cpp

Z80_misc.o: Z80_misc.cpp Z80.h \
		defs.h \
		Reg16.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Z80_misc.o Z80_misc.cpp

pboWidget.o: pboWidget.cpp pboWidget.h \
		CRTScreen.h \
		defs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pboWidget.o pboWidget.cpp

speedcontroller.o: speedcontroller.cpp speedcontroller.h \
		SoundThread.h \
		defs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o speedcontroller.o speedcontroller.cpp

qrc_screen_frame.o: qrc_screen_frame.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_screen_frame.o qrc_screen_frame.cpp

moc_Debugger.o: moc_Debugger.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Debugger.o moc_Debugger.cpp

moc_EmulatorThread.o: moc_EmulatorThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_EmulatorThread.o moc_EmulatorThread.cpp

moc_SoundThread.o: moc_SoundThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SoundThread.o moc_SoundThread.cpp

moc_enterbytesdialog.o: moc_enterbytesdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_enterbytesdialog.o moc_enterbytesdialog.cpp

moc_graphicsinspector.o: moc_graphicsinspector.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graphicsinspector.o moc_graphicsinspector.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/cadence/bin || mkdir -p $(INSTALL_ROOT)/opt/cadence/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/cadence/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/cadence/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/cadence/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/cadence/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

.SUFFIXES:

